language: java
sudo: true
dist: trusty
jdk: oraclejdk9
script:
  mvn install -DskipTests=false -Dmaven.javadoc.skip=false -B -V
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw